//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beauty_Store.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class complain
    {
        [Display(Name ="Complain ID")]
        public int complain_id { get; set; }
        [Display(Name = "User ID")]
        public int userid { get; set; }
        [Display(Name = "Code")]
        public string saleCode { get; set; }
        [Required]
        [Display(Name = "Complain")]
        [MaxLength(1000)]
        public string complain1 { get; set; }
    }
}
