//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beauty_Store.Models
{
    using Beauty_Store.validationAttributes;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class product
    {
        [Display(Name = "Product ID")]
        public int product_id { get; set; }
        [Required]
        [Display(Name ="Product Name")]
        public string product_name { get; set; }
        [Required]
        [Display(Name = "Category")]
        public string product_type { get; set; }
        [Required]
        [Display(Name = "Price")]
        [MinimumValue(ErrorMessage ="Price Cannot be Less Than 1 L.E.")]
        public double price { get; set; }
        [Display(Name = "Production Year")]
        public Nullable<int> year { get; set; }
        [Display(Name = "Discount")]
        [MaximumValue(ErrorMessage = "Discount Cannot be More Than 50%")]
        public Nullable<int> discount_per { get; set; }
        [Display(Name = "Shipping Expenses")]
        public Nullable<double> shipping_exp { get; set; }
        [Display(Name = "Product Picture")]
        public string product_img { get; set; }
    }
}
